name: pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - psycopg2=2.9.3
  - pip:
      - pandas==1.4.0
      - python-decouple==3.6
      - requests==2.28.1
      - SQLAlchemy==1.4.39
